#!perl
use v5.32;
use strict;

use lib qw(lib);
use experimental qw(signatures);

use Clockify;

use Mojo::Util qw(dumper);

my $user = Clockify->current_user;

say "User ID: ", $user->id;
say "Active Workspace ID: ", $user->active_workspace_id;

my $projects = Clockify->all_projects( $user->active_workspace_id );

foreach my $project ( $projects->@* ) {
	say join " ", $project->id, $project->name
	}
